# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  # Allows manual trigger
  workflow_dispatch:

# Memberikan izin agar GITHUB_TOKEN bisa push ke repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Generate snake GIF & SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: TangkasAgus28
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Cek status git (opsional, untuk debug)
      - run: git status

      # Push hasil generate ke branch master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Deploy file ke branch `output` (biasanya untuk GitHub Pages)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
